title: IT Gurukula
email: itgurukulanp@gmail.com
description: >-
  Providing IT Education based on ancient Gurukul education system.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itgurukula.org"
image_base_url: /assets/img

google_analytics: G-2E4C5RS3T5

# Build settings
markdown: kramdown
